Repository hansung-PreCaps/Backend, pull requests merged in 2024-10, with the labels that each got.

#2 [feat] 공통 응답 코드 구현 & 공통 예외 처리
  build.gradle
  src/main/java/com/pictalk/global/HealthController.java
  src/main/java/com/pictalk/global/exception/ExceptionAdvice.java
  src/main/java/com/pictalk/global/exception/GeneralException.java
  src/main/java/com/pictalk/global/payload/CommonResponse.java
  src/main/java/com/pictalk/global/payload/ReasonDto.java
  src/main/java/com/pictalk/global/payload/status/BaseStatus.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/global/payload/status/SuccessStatus.java
Labels: 🚀 Feat, 🏷 Fix

#5 feat: test
  src/main/java/com/pictalk/global/exception/ExceptionAdvice.java
Labels: 🚀 Feat, 📁 Test

#7 chore: pr reviewer 자동 설정 및 ai code review설정
  .github/CODEOWNERS
Labels: 🧭 Chore

#8 Create codereview.yml
  .github/workflows/codereview.yml
Labels: 🧭 Chore

#10 chore: backend-ci
  .github/workflows/backend-ci.yml
  build.gradle
  src/test/resources/application.yml
Labels: 🧭 Chore

#20 [feat] 회원가입 및 로그인 구현
  .gitignore
  build.gradle
  compose.yaml
  src/main/java/com/pictalk/global/common/BaseEntity.java
  src/main/java/com/pictalk/global/config/SecurityConfig.java
  src/main/java/com/pictalk/global/config/SwaggerConfig.java
  src/main/java/com/pictalk/global/jwt/JwtRequestFilter.java
  src/main/java/com/pictalk/global/jwt/JwtService.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/group/domain/Group.java
  src/main/java/com/pictalk/user/controller/UserController.java
  src/main/java/com/pictalk/user/converter/UserConverter.java
  src/main/java/com/pictalk/user/domain/User.java
  src/main/java/com/pictalk/user/domain/dto/UserRequestDto.java
  src/main/java/com/pictalk/user/domain/dto/UserResponseDto.java
  src/main/java/com/pictalk/user/repository/UserRepository.java
  src/main/java/com/pictalk/user/service/MyUserDetailsService.java
  src/main/java/com/pictalk/user/service/UserService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🧭 Chore, 🚀 Feat
