Repository hansung-PreCaps/Backend, pull requests merged in 2024-11, with the labels that each got.

#28 CI/CD 파이프라인 구축
  .ebextensions/00-makeFiles.config
  .ebextensions/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/resources/application.yml
Labels: 🧭 Chore, 🚀 Feat

#29 CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
Labels: 🧭 Chore, 🚀 Feat, 🏷 Fix

#30 CI/CD 파이프라인 구축
  src/main/java/com/pictalk/global/config/SecurityConfig.java
Labels: 🧭 Chore, 🚀 Feat, 🏷 Fix, 🧹 Refactor

#32 AI message 생성 및 image 생성
  build.gradle
  src/main/java/com/pictalk/aiimage/controller/AiImageController.java
  src/main/java/com/pictalk/aiimage/domain/Image.java
  src/main/java/com/pictalk/aiimage/dto/ImageRequestDto.java
  src/main/java/com/pictalk/aiimage/dto/ImageResponseDto.java
  src/main/java/com/pictalk/aiimage/service/AiImageService.java
  src/main/java/com/pictalk/global/component/OpenAIClient.java
  src/main/java/com/pictalk/global/component/OpenAIImageClient.java
  src/main/java/com/pictalk/global/config/ObjectMapperConfig.java
  src/main/java/com/pictalk/global/config/SecurityConfig.java
  src/main/java/com/pictalk/global/jwt/JwtRequestFilter.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/global/vo/Image.java
  src/main/java/com/pictalk/global/vo/ImageType.java
  src/main/java/com/pictalk/message/controller/AIMessageController.java
  src/main/java/com/pictalk/message/domain/Message.java
  src/main/java/com/pictalk/message/dto/MessageRequestDto.java
  src/main/java/com/pictalk/message/dto/MessageResponseDto.java
  src/main/java/com/pictalk/message/service/AIMessageService.java
  src/main/java/com/pictalk/user/controller/UserController.java
  src/main/java/com/pictalk/user/converter/UserConverter.java
  src/main/java/com/pictalk/user/dto/UserRequestDto.java
  src/main/java/com/pictalk/user/dto/UserResponseDto.java
  src/main/java/com/pictalk/user/service/UserService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🚀 Feat

#31 [feat] 문자 전송 API 1차 구현
  src/main/java/com/pictalk/aiimage/domain/Image.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/message/controller/MessageController.java
  src/main/java/com/pictalk/message/domain/Message.java
  src/main/java/com/pictalk/message/domain/Receiver.java
  src/main/java/com/pictalk/message/domain/Sender.java
  src/main/java/com/pictalk/message/dto/MessageRequestDto.java
  src/main/java/com/pictalk/message/dto/MessageResponseDto.java
  src/main/java/com/pictalk/message/repository/MessageRepository.java
  src/main/java/com/pictalk/message/repository/ReceiverRepository.java
  src/main/java/com/pictalk/message/repository/SenderRepository.java
  src/main/java/com/pictalk/message/service/ImmediateMessageService.java
  src/main/java/com/pictalk/message/service/MessageService.java
  src/main/java/com/pictalk/message/service/ScheduledMessageService.java
  src/main/java/com/pictalk/user/dto/UserRequestDto.java
Labels: 🚀 Feat

#35 refactor: nginx.conf의 CORS 설정 제거
  .platform/nginx.conf
  src/main/resources/application.yml
Labels: 🧭 Chore, 🧹 Refactor

#44 S3 연동 및 이미지 업로드
  build.gradle
  src/main/java/com/pictalk/aiimage/domain/Image.java
  src/main/java/com/pictalk/global/config/AmazonS3Config.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/global/payload/status/SuccessStatus.java
  src/main/java/com/pictalk/global/util/ImageUtil.java
  src/main/java/com/pictalk/infra/S3Uploader.java
  src/main/java/com/pictalk/message/controller/ImageController.java
  src/main/java/com/pictalk/message/domain/Message.java
  src/main/java/com/pictalk/message/domain/MessageImage.java
  src/main/java/com/pictalk/message/repository/MessageImageRepository.java
  src/main/java/com/pictalk/message/service/MessageImageService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🧭 Chore, 🚀 Feat

#48 이미지 조회 로직 작성
  src/main/java/com/pictalk/global/config/ModelResolverConfig.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/global/payload/status/SuccessStatus.java
  src/main/java/com/pictalk/message/controller/ImageController.java
  src/main/java/com/pictalk/message/controller/MessageController.java
  src/main/java/com/pictalk/message/dto/ImageResponseDto.java
  src/main/java/com/pictalk/message/dto/MessageResponseDto.java
  src/main/java/com/pictalk/message/repository/MessageImageRepository.java
  src/main/java/com/pictalk/message/service/MessageImageService.java
  src/main/java/com/pictalk/message/service/MessageService.java
Labels: 🚀 Feat

#50 주소록 기능 완성
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/global/payload/status/SuccessStatus.java
  src/main/java/com/pictalk/group/controller/GroupController.java
  src/main/java/com/pictalk/group/controller/GroupReceiverController.java
  src/main/java/com/pictalk/group/domain/Group.java
  src/main/java/com/pictalk/group/domain/GroupReceiver.java
  src/main/java/com/pictalk/group/dto/GroupRequestDto.java
  src/main/java/com/pictalk/group/dto/GroupResponseDto.java
  src/main/java/com/pictalk/group/repository/GroupReceiverRepository.java
  src/main/java/com/pictalk/group/repository/GroupRepository.java
  src/main/java/com/pictalk/group/service/GroupReceiverService.java
  src/main/java/com/pictalk/group/service/GroupService.java
  src/main/java/com/pictalk/group/service/facade/CreateGroupReceiverFacade.java
  src/main/java/com/pictalk/message/domain/Receiver.java
  src/main/java/com/pictalk/message/service/ReceiverService.java
Labels: 🚀 Feat

#63 [fix] AI 이미지 생성 정확도 향상을 위한 프롬프트 템플릿 개선
  src/main/java/com/pictalk/image/service/AiImageService.java
Labels: 🏷 Fix

#65 [fix] AI 생성 메시지에 이모지가 포함되지 않도록 프롬프트 수정
  src/main/java/com/pictalk/message/service/AIMessageService.java
Labels: 🏷 Fix

#67 뿌리오 문자 전송 구현
  src/main/java/com/pictalk/global/component/PpurioClient.java
  src/main/java/com/pictalk/global/config/AmazonS3Config.java
  src/main/java/com/pictalk/global/config/PpurioConfig.java
  src/main/java/com/pictalk/global/config/SwaggerConfig.java
  src/main/java/com/pictalk/global/payload/status/ErrorStatus.java
  src/main/java/com/pictalk/global/util/ImageUtil.java
  src/main/java/com/pictalk/group/domain/Group.java
  src/main/java/com/pictalk/group/domain/GroupReceiver.java
  src/main/java/com/pictalk/infra/PpurioService.java
  src/main/java/com/pictalk/infra/S3Uploader.java
  src/main/java/com/pictalk/message/controller/ImageController.java
  src/main/java/com/pictalk/message/controller/MessageController.java
  src/main/java/com/pictalk/message/domain/Message.java
  src/main/java/com/pictalk/message/domain/MessageImage.java
  src/main/java/com/pictalk/message/domain/Receiver.java
  src/main/java/com/pictalk/message/domain/Sender.java
  src/main/java/com/pictalk/message/dto/MessageRequestDto.java
  src/main/java/com/pictalk/message/dto/MessageResponseDto.java
  src/main/java/com/pictalk/message/dto/PpurioRequestDto.java
  src/main/java/com/pictalk/message/dto/PpurioResponseDto.java
  src/main/java/com/pictalk/message/repository/MessageRepository.java
  src/main/java/com/pictalk/message/repository/ReceiverRepository.java
  src/main/java/com/pictalk/message/repository/SenderRepository.java
  src/main/java/com/pictalk/message/service/MessageImageService.java
  src/main/java/com/pictalk/message/service/MessageService.java
  src/main/java/com/pictalk/message/service/MessageServiceImpl.java
  src/main/java/com/pictalk/message/service/ReceiverService.java
  src/main/java/com/pictalk/message/service/SenderService.java
  src/main/java/com/pictalk/message/service/facade/SendMessageService.java
  src/main/java/com/pictalk/message/service/facade/SendSendMessageFacade.java
  src/main/java/com/pictalk/user/domain/User.java
  src/main/java/com/pictalk/user/service/UserService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🚀 Feat

#68 [feat] 그룹 이름 조회 API 추가
  src/main/java/com/pictalk/global/payload/status/SuccessStatus.java
  src/main/java/com/pictalk/group/controller/GroupController.java
  src/main/java/com/pictalk/group/service/GroupService.java
Labels: 🚀 Feat

#79 refactor: url을 s3 url로 변경
  src/main/java/com/pictalk/global/util/UrlImageDownloadUtil.java
  src/main/java/com/pictalk/image/controller/AiImageController.java
  src/main/java/com/pictalk/image/service/AiImageService.java
  src/main/java/com/pictalk/infra/S3Uploader.java
  src/main/java/com/pictalk/message/controller/AIMessageController.java
Labels: 🧹 Refactor
